version: '3.8'

services:
  postgresql:
    build:
      context: ./docker/postgresql
    container_name: authentik_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: authentikpass
      POSTGRES_DB: authentikdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    build:
      context: ./docker/redis
    container_name: authentik_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  server:
    build:
      context: ./docker/server
    container_name: authentik_server
    depends_on:
      - postgresql
      - redis
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://authentik:authentikpass@postgresql:5432/authentikdb
      REDIS_URL: redis://redis:6379/0

  worker:
    build:
      context: ./docker/worker
    container_name: authentik_worker
    depends_on:
      - redis
      - postgresql
    environment:
      DATABASE_URL: postgres://authentik:authentikpass@postgresql:5432/authentikdb
      REDIS_URL: redis://redis:6379/0

  nginx:
    build:
      context: ./docker/nginx
    container_name: authentik_nginx
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
