apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-postgresql
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql