{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik-chart.postgresql.fullname" . }}
  labels:
    {{- include "authentik-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "authentik-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}