apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-redis
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis