apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik-chart.fullname" . }}-secret
  labels:
    {{- include "authentik-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentik-chart.fullname" . }}-postgresql-secret
  labels:
    {{- include "authentik-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
{{- end }}