apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-server
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "authentik.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server