apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik-chart.fullname" . }}
  labels:
    {{- include "authentik-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "authentik-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server