  name: Import secrets from Vault
  run: |
    set -e

    # Install vault CLI if not present
    if ! command -v vault &> /dev/null; then
      VAULT_VERSION="1.15.2"
      wget -O vault.zip "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
      unzip vault.zip
      sudo mv vault /usr/local/bin/
      sudo chmod +x /usr/local/bin/vault
      rm vault.zip
    fi

    # Set Vault address
    export VAULT_ADDR=${{ env.VAULT_ADDR }}
    echo "Vault Addr: $VAULT_ADDR"

    echo "Checking Vault availability..."
    curl --fail --silent $VAULT_ADDR/v1/sys/health || {
      echo "❌ Vault not available at $VAULT_ADDR"
      exit 1
    }

    echo "Authenticating to Vault..."
    timeout 10 vault auth -method=token token=${{ secrets.VAULT_TOKEN }} || {
      echo "❌ Vault token authentication failed or timed out"
      exit 1
    }

    echo "Ensuring Vault path exists..."
    vault kv put ${{ env.VAULT_PATH }} temp=temp 2>/dev/null || true

    echo "Retrieving secrets from Vault..."
    vault kv get -format=json ${{ env.VAULT_PATH }} | jq -r \
      '.data.data | to_entries[] | "export \(.key | ascii_upcase)=\(.value)"' > vault_secrets.env

    echo "Sourcing secrets from vault_secrets.env"
    source vault_secrets.env

    echo "Injecting environment variables..."
    echo "POSTGRES_PASSWORD=$PG_PASS" >> $GITHUB_ENV
    echo "AUTHENTIK_SECRET_KEY=$AUTHENTIK_SECRET_KEY" >> $GITHUB_ENV
    echo "SMTP_HOST=$SMTP_HOST" >> $GITHUB_ENV
    echo "SMTP_PORT=$SMTP_PORT" >> $GITHUB_ENV
    echo "SMTP_USER=$SMTP_USER" >> $GITHUB_ENV
    echo "SMTP_PASS=$SMTP_PASS" >> $GITHUB_ENV
    echo "DOMAIN_NAME=$DOMAIN_NAME" >> $GITHUB_ENV

    echo "✅ Vault secret injection completed."

